### ISSUE TITLE
MPI coverage in stage input_iterator

### ISSUE THREAD

**Issue by grantmerz** [LSSTDESC/rail_base#116]
In the input_iterator of a RailStage, there is no coverage [here](https://github.com/LSSTDESC/rail_base/blob/ca6cfda6a801932882e624f3f9b42d6b0c1ce11e/src/rail/core/stage.py#L352) if mpi is not set up.  if `self.comm=None ` then an AttributeError is raised

**Comment by eacharles** [comment]
Fixed in #117
