### ISSUE TITLE
estimate command line doesn't include ability to grab catalog tag

### ISSUE THREAD

**Issue by sschmidt23** [LSSTDESC/rail_base#148]
** Feature request**
would be nice to be able to include a catalog tag to update params for specific catalogs in estimate, super easy to add this

**Before submitting**
Please check the following:

- [x] I have described the purpose of the suggested change, specifying what I need the enhancement to accomplish, i.e. what problem it solves.
- [ ] I have included any relevant links, screenshots, environment information, and data relevant to implementing the requested feature, as well as pseudocode for how I want to access the new functionality.
- [ ] If I have ideas for how the new feature could be implemented, I have provided explanations and/or pseudocode and/or task lists for the steps.

**Comment by eacharles** [comment]
#149
