### ISSUE TITLE
TableHandle._size returns 0 on any exception

### ISSUE THREAD

**Issue by joezuntz** [LSSTDESC/rail_base#155]
Currently the TableHandle._size method tries to open an HDF5 table but catches all exceptions. So if there is any error whatsoever (e.g. wrong group name) then later things go silently wrong. In conjunction with the other issue I just opened this means that you can get silent sys.exit() calls with no traceback.

I don't know what kinds of errors you're expecting to pick up here but the current catch is too broad.

**Comment by eacharles** [comment]
done with #158
