### ISSUE TITLE
`Param` class completeness

### ISSUE THREAD

**Issue by aimalz** [LSSTDESC/rail_base#30]
Users should be able to access the list of all possible config parameters for a stage as well as information about them, such as their types, default values, and a description of what a value for the parameter means. Some stages use the `ceci` `Param` class to contain that information, but it doesn't seem to have a `__repr__()` method to make it human-readable. Once LSSTDESC/ceci#94 is done, we'll be ready for this issue to homogenize config parameters of all stages to the `Param` class.

**Comment by eacharles** [comment]
Done in ceci.
