### ISSUE TITLE
Adding support to parquet files in input_iterator

### ISSUE THREAD

**Issue by joselotl** [LSSTDESC/rail_base#80]
**Bug report**
With the recent changes in the input_iterator, the parquet files are not working. New functions added to tables_io should allow for the parquet files to be read in chunks.

**Before submitting**
Please check the following:

- [ ] I have described the situation in which the bug arose, including what code was executed, information about my environment, and any applicable data others will need to reproduce the problem.
- [ ] I have included available evidence of the unexpected behavior (including error messages, screenshots, and/or plots) as well as a descriprion of what I expected instead.
- [ ] If I have a solution in mind, I have provided an explanation and/or pseudocode and/or task list.

**Comment by eacharles** [comment]
closed with https://github.com/LSSTDESC/tables_io/pull/88
