### ISSUE TITLE
Adding base classes for creation

### ISSUE THREAD

**Issue by ztq1996** [LSSTDESC/rail_base#90]
All creation/degradation can be divided into two kinds of degradation type:
1. add noise to the input catalog
2. make cuts/selections

I propose to call the first one "noisifier" or "noiseAdder", and the second one "selector"

Here are the baby steps:
1. Create noisifier.py, and a noisifier class in it. The noisifier should have function to check the length of the input and output to be the same. There should be a dummy noisifier that add no noise to it. 
2. Create selector.py, and a selector class in it. 
3. Add a deprecation warning to degrader class in the degrader.py. We won't remove degrader.py until all subclasses has finished migrating to the new parent classes.

**Comment by eacharles** [comment]
closed with #96
